name: Build and Deploy to Azure
on:
  push:
    branches: [ "master" ] # Triggers the CI/CD pipeline on code pushes to the 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the GitHub repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure CLI
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Log in to Azure Container Registry
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: airbnbintial.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build --no-cache -t airbnbintial.azurecr.io/airbnb-api:1.0 .
        docker push airbnbintial.azurecr.io/airbnb-api:1.0

    # Step 5: Deploy to Azure Web App using Publish Profile
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: airbnbprediction
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'airbnbintial.azurecr.io/airbnb-api:1.0'

    # Step 6: Restart Azure Web App
    - name: Restart Azure Web App
      run: |
        az webapp restart --name airbnbprediction --resource-group endendml_group
